name: Build and Publish LifeDash

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Kodu İndir (Checkout)
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Install build tools
        run: npm install --global windows-build-tools --quiet

      - name: Rebuild native modules
        run: npm run rebuild

      - name: Build ve Publish (Electron Builder)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
